// Code generated by lua_to_go. DO NOT EDIT.
package atlases

import (
	"remembering-home/src/common"
	"remembering-home/src/enums"
)

var AtlasStorageRoom = AtlasData{
	Frames: []FrameData{
		{
			ID:   enums.ItemTires,
			Pos:  common.Vec2{X: 201, Y: 52},
			Size: common.Vec2{X: 35, Y: 22},
		},
		{
			ID:   enums.ItemFilingCabinet,
			Pos:  common.Vec2{X: 303, Y: 4},
			Size: common.Vec2{X: 19, Y: 44},
		},
		{
			ID:   enums.ItemBulb,
			Pos:  common.Vec2{X: 330, Y: 4},
			Size: common.Vec2{X: 5, Y: 18},
		},
		{
			ID:   enums.ItemLightSwitch,
			Pos:  common.Vec2{X: 244, Y: 52},
			Size: common.Vec2{X: 13, Y: 17},
		},
		{
			ID:   enums.ItemLadder,
			Pos:  common.Vec2{X: 4, Y: 4},
			Size: common.Vec2{X: 111, Y: 70},
		},
		{
			ID:   enums.ItemTable,
			Pos:  common.Vec2{X: 201, Y: 4},
			Size: common.Vec2{X: 59, Y: 40},
		},
		{
			ID:   enums.ItemShelf,
			Pos:  common.Vec2{X: 123, Y: 4},
			Size: common.Vec2{X: 70, Y: 60},
		},
		{
			ID:   enums.ItemShelfSide,
			Pos:  common.Vec2{X: 268, Y: 4},
			Size: common.Vec2{X: 27, Y: 70},
		},
		{
			ID:   enums.ItemLeftDoor,
			Pos:  common.Vec2{X: 343, Y: 4},
			Size: common.Vec2{X: 4, Y: 65},
		},
		{
			ID:   enums.ItemRightDoor,
			Pos:  common.Vec2{X: 355, Y: 4},
			Size: common.Vec2{X: 4, Y: 65},
		},
		{
			ID:   enums.ItemBarrell,
			Pos:  common.Vec2{X: 303, Y: 56},
			Size: common.Vec2{X: 32, Y: 22},
		},
	},
	Metadata: Metadata{
		Padding:   4,
		Extrude:   0,
		Size:      common.Vec2{X: 363, Y: 82},
		QuadCount: 11,
	},
}
