// Code generated by lua_to_go. DO NOT EDIT.
package items

import (
	"remembering-home/src/common"
	"remembering-home/src/dialogues"
	"remembering-home/src/enums"
)

var ItemStorageRoom = []ItemData{
	{
		Item:  enums.ItemBulb,
		Pos:   common.Vec2{X: 90, Y: 16},
		NoCol: true,
	},
	{
		Item:  enums.ItemBulb,
		Name:  "bulb2",
		Pos:   common.Vec2{X: 240, Y: 16},
		NoCol: true,
	},
	{
		Item:      enums.ItemLeftDoor,
		Pos:       common.Vec2{X: 16, Y: 31},
		ReqColDir: enums.DirectionLeft,
		Tags:      []enums.ItemClass{enums.ItemClassDoor},
	},
	{
		Item:      enums.ItemRightDoor,
		Pos:       common.Vec2{X: 332, Y: 47},
		ReqColDir: enums.DirectionRight,
		Tags:      []enums.ItemClass{enums.ItemClassDoor},
	},
	{
		Item: enums.ItemLightSwitch,
		Pos:  common.Vec2{X: 64, Y: 48},
		Dialogue: dialogues.DialogueKeys{
			Room: enums.RoomStorageRoom,
			Item: enums.ItemLightSwitch,
		},
	},
	{
		Item:  enums.ItemLadder,
		Pos:   common.Vec2{X: 97, Y: 42},
		NoCol: true,
	},
	{
		Item: enums.ItemShelf,
		Pos:  common.Vec2{X: 208, Y: 52},
		Dialogue: dialogues.DialogueKeys{
			Room: enums.RoomStorageRoom,
			Item: enums.ItemShelf,
		},
	},
	{
		Item:  enums.ItemShelfSide,
		Pos:   common.Vec2{X: 309, Y: 42},
		NoCol: true,
	},
	{
		Item: enums.ItemTable,
		Pos:  common.Vec2{X: 102, Y: 72},
		Dialogue: dialogues.DialogueKeys{
			Room: enums.RoomStorageRoom,
			Item: enums.ItemTable,
		},
	},
	{
		Item: enums.ItemTires,
		Pos:  common.Vec2{X: 107, Y: 91},
	},
	{
		Item: enums.ItemFilingCabinet,
		Pos:  common.Vec2{X: 180, Y: 68},
		Dialogue: dialogues.DialogueKeys{
			Room: enums.RoomStorageRoom,
			Item: enums.ItemFilingCabinet,
		},
	},
	{
		Item:  enums.ItemBarrell,
		Pos:   common.Vec2{X: 76, Y: 90},
		NoCol: true,
	},
	{
		Item:  enums.ItemBarrell,
		Name:  "barrell2",
		Pos:   common.Vec2{X: 142, Y: 90},
		NoCol: true,
	},
	{
		Item:  enums.ItemBarrell,
		Name:  "barrell3",
		Pos:   common.Vec2{X: 264, Y: 90},
		NoCol: true,
	},
}
