// Code generated by lua_to_go. DO NOT EDIT.
package items

import (
	"remembering-home/src/common"
	"remembering-home/src/dialogues"
	"remembering-home/src/enums"
)

var ItemUtilityRoom = []ItemData{
	{
		Item:  enums.ItemBulb,
		Pos:   common.Vec2{X: 90, Y: 16},
		NoCol: true,
	},
	{
		Item:  enums.ItemBulb,
		Name:  "bulb2",
		Pos:   common.Vec2{X: 240, Y: 16},
		NoCol: true,
	},
	{
		Item: enums.ItemLightSwitch,
		Pos:  common.Vec2{X: 48, Y: 50},
		Dialogue: dialogues.DialogueKeys{
			Room: enums.RoomUndefined,
			Item: enums.ItemLightSwitch,
		},
	},
	{
		Item: enums.ItemShelf,
		Pos:  common.Vec2{X: 136, Y: 57},
		Dialogue: dialogues.DialogueKeys{
			Room: enums.RoomUndefined,
			Item: enums.ItemShelf,
		},
	},
	{
		Item: enums.ItemUndefined,
		Pos:  common.Vec2{X: 316, Y: 48},
		Dialogue: dialogues.DialogueKeys{
			Room: enums.RoomUndefined,
			Item: enums.ItemUndefined,
		},
	},
	{
		Item:  enums.ItemUndefined,
		Pos:   common.Vec2{X: 128, Y: 69},
		NoCol: true,
	},
	{
		Item: enums.ItemUndefined,
		Pos:  common.Vec2{X: 260, Y: 76},
		Dialogue: dialogues.DialogueKeys{
			Room: enums.RoomUndefined,
			Item: enums.ItemUndefined,
		},
	},
	{
		Item:  enums.ItemUndefined,
		Pos:   common.Vec2{X: 110, Y: 60},
		NoCol: true,
	},
	{
		Item: enums.ItemUndefined,
		Pos:  common.Vec2{X: 0, Y: 0},
		Dialogue: dialogues.DialogueKeys{
			Room: enums.RoomUndefined,
			Item: enums.ItemUndefined,
		},
	},
	{
		Item:  enums.ItemUndefined,
		Name:  "wood1",
		Pos:   common.Vec2{X: 74, Y: 96},
		NoCol: true,
	},
	{
		Item:  enums.ItemUndefined,
		Name:  "wood2",
		Pos:   common.Vec2{X: 89, Y: 96},
		NoCol: true,
	},
	{
		Item:  enums.ItemUndefined,
		Name:  "wood3",
		Pos:   common.Vec2{X: 79, Y: 79},
		NoCol: true,
	},
	{
		Item:  enums.ItemUndefined,
		Name:  "wood4",
		Pos:   common.Vec2{X: 194, Y: 96},
		NoCol: true,
	},
	{
		Item:  enums.ItemUndefined,
		Name:  "wood5",
		Pos:   common.Vec2{X: 240, Y: 96},
		NoCol: true,
	},
	{
		Item:  enums.ItemUndefined,
		Name:  "wood6",
		Pos:   common.Vec2{X: 284, Y: 96},
		NoCol: true,
	},
}
